compilers=&mach
defaultCompiler=mach510
compilerType=mach
objdumper=/opt/compiler-explorer/gcc-16.2.0/bin/objdump
llvmObjdumper=/opt/compiler-explorer/clang-trunk/bin/llvm-objdump
supportsBinary=true
supportsBinaryObject=true
supportsExecute=true
supportsLibraryCodeFilter=true
binaryHideFuncRe=^(std\..*|_start|.*@plt.*)$

group.mach.compilers=mach510
group.mach.isSemVer=true
group.mach.baseName=mach
group.mach.versionFlag=info|--version
group.mach.licenseLink=https://github.com/briar-systems/mach/blob/main/LICENSE
group.mach.licenseName=MIT License

compiler.mach510.exe=/opt/compiler-explorer/mach-5.1.0/mach
compiler.mach510.semver=5.1.0
