compilers=&mach
defaultCompiler=mach
compilerType=mach
objdumper=objdump
llvmObjdumper=llvm-objdump
supportsBinary=true
supportsBinaryObject=true
supportsExecute=true
supportsLibraryCodeFilter=true
binaryHideFuncRe=^(std\..*|_start|.*@plt.*)$

group.mach.compilers=mach
group.mach.isSemVer=true
group.mach.baseName=mach
group.mach.versionFlag=info|--version

compiler.mach.exe=/usr/local/bin/mach
