compilers=&mach
defaultCompiler=mach
compilerType=mach
versionFlag=info|--version
isSemVer=true
objdumper=objdump
llvmObjdumper=llvm-objdump
supportsBinary=true
supportsBinaryObject=true
supportsExecute=true
supportsLibraryCodeFilter=true
binaryHideFuncRe=^(std\..*|_start|.*@plt.*)$

group.mach.compilers=mach
compiler.mach.exe=/usr/local/bin/mach
compiler.mach.name=mach
compiler.mach.stdPath=/usr/local/lib/mach/std
